#!/bin/bash

if ssh-add -L | grep macpc ; then
  echo ok # nothing
else
  ssh-add ~/.ssh/mac_id_rsa_2
fi

# set -e ## error
set -x

git add .
git commit -m "autobuild `date "+%Y%m%d"`"
git push


gem build wco_email.gemspec
gem push wco_email-$version.gem

rm wco_email-`cat VERSION`.gem

echo "wco_email build ok"
