#!/usr/bin/env ruby

def puts! a, b=''
  puts "+++ +++ #{b}"
  puts a.inspect
end

a = `service microsites3_api-app status | grep "start/running"`
b = $?.exitstatus

if b.to_i == 1
  puts "service not running!"
else
  puts "service ok"
end

exit b
